In [1]:
## Importing the necessary library
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import sklearn as sl
from sklearn.feature_selection import SelectKBest, chi2, mutual_info_classif
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [2]:
# Read the Datasetof training data
df = pd.read_csv("/content/drive/MyDrive/Assignment_Train.csv")

In [3]:
df.head()

,DEALER ID,APPLICATION LOGIN DATE,HDB BRANCH NAME,HDB BRANCH STATE,FIRST NAME,MIDDLE NAME,LAST NAME,mobile,AADHAR VERIFIED,Cibil Score,...,Phone Social Premium.shaadi,Phone Social Premium.skype,Phone Social Premium.toi,Phone Social Premium.whatsapp,Phone Social Premium.yatra,Phone Social Premium.zoho,phone_digitalage,phone_nameMatchScore,phone_phoneFootprintStrengthOverall,Application Status
0,106989,07/20/2022,DELHI-SF,DELHI,SUNIL,NaN,CHANDER,9210574080,NO,726,...,0.0,0.0,1.0,NaN,NaN,0.0,5324.0,67.222222,High,APPROVED
1,108975,07/28/2022,PATNA-SF,BIHAR,AMRIT,NaN,KUMAR,8877987018,NO,NaN,...,0.0,0.0,0.0,NaN,NaN,0.0,1998.0,100.000000,High,APPROVED
2,111004,07/15/2022,DARJEELING-SF,WEST BENGAL,ANIMESH,NaN,THAPA,8910862135,NO,737,...,0.0,0.0,0.0,NaN,NaN,0.0,-1.0,-1.000000,Low,APPROVED
3,192020,07/04/22,SAHARANPUR-SF,UTTAR PRADESH,ADITYA,NaN,SINGH,9758428017,NO,713,...,0.0,0.0,1.0,NaN,NaN,0.0,1998.0,72.777778,High,APPROVED
4,55095,07/15/2022,MODASA-SF,GUJARAT,PARMAR,HARESHBHAI,AMRUTBHAI,9687028486,NO,669,...,0.0,0.0,1.0,NaN,NaN,0.0,1998.0,68.095238,High,DECLINED

In [4]:
## Make a list of redundant columns
df_list = ["APPLICATION LOGIN DATE", "HDB BRANCH STATE", "FIRST NAME", "MIDDLE NAME", "LAST NAME", "mobile" , "DEALER NAME", "ASSET CTG", "ASSET MODEL NO", "PRIMARY ASSET MAKE", "Primary Asset Model No", "Personal Email Address", "DOB", "EMPLOYER NAME", "EMPLOYER TYPE", "Pan Name", "name", "upi_name", "Phone Social Premium.a23games", "Phone Social Premium.isWABusiness", "Phone Social Premium.jiomart", "Phone Social Premium.my11", "Phone Social Premium.rummycircle", "Phone Social Premium.whatsapp", "Phone Social Premium.yatra", "phone_digitalage", "phone_nameMatchScore"]

In [5]:
# Drop redundant columns
df.drop(labels = df_list, axis=1, inplace = True)

In [6]:
df.shape

(10000, 28)

In [7]:
df.head()

,DEALER ID,HDB BRANCH NAME,AADHAR VERIFIED,Cibil Score,MOBILE VERIFICATION,TOTAL ASSET COST,APPLIED AMOUNT,MARITAL STATUS,GENDER,AGE,...,Phone Social Premium.instagram,Phone Social Premium.jeevansaathi,Phone Social Premium.microsoft,Phone Social Premium.paytm,Phone Social Premium.shaadi,Phone Social Premium.skype,Phone Social Premium.toi,Phone Social Premium.zoho,phone_phoneFootprintStrengthOverall,Application Status
0,106989,DELHI-SF,NO,726,True,95041.0,85000,Married,Male,44,...,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0,High,APPROVED
1,108975,PATNA-SF,NO,NaN,True,NaN,90000,NaN,Male,25,...,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,High,APPROVED
2,111004,DARJEELING-SF,NO,737,True,119436.0,75000,Single,Male,22,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Low,APPROVED
3,192020,SAHARANPUR-SF,NO,713,True,87000.0,78500,Single,Male,24,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,High,APPROVED
4,55095,MODASA-SF,NO,669,True,NaN,70000,NaN,Male,33,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,High,DECLINED

In [8]:
## Check the missing values in each feature
df.isnull().sum()

DEALER ID                                 0
HDB BRANCH NAME                           1
AADHAR VERIFIED                           0
Cibil Score                            4297
MOBILE VERIFICATION                       0
TOTAL ASSET COST                       5108
APPLIED AMOUNT                            0
MARITAL STATUS                         4894
GENDER                                    0
AGE                                       0
ADDRESS TYPE                           3312
EMPLOY CONSTITUTION                    4998
vpa                                    2787
Phone Social Premium.amazon            1916
Phone Social Premium.byjus             1948
Phone Social Premium.flipkart          1832
Phone Social Premium.housing           1776
Phone Social Premium.indiamart         1775
Phone Social Premium.instagram         6630
Phone Social Premium.jeevansaathi      1829
Phone Social Premium.microsoft         1872
Phone Social Premium.paytm             1757
Phone Social Premium.shaadi            1779
Phone Social Premium.skype             1785
Phone Social Premium.toi               1943
Phone Social Premium.zoho              1782
phone_phoneFootprintStrengthOverall       6
Application Status                        0
dtype: int64

In [9]:
## Find the mode of Categorical feature HDB Branch name
df["HDB BRANCH NAME"].mode()[0]

'NOIDA-SF'

In [10]:
# Fill all the Blank values with mode
df["HDB BRANCH NAME"].fillna(df["HDB BRANCH NAME"].mode()[0], inplace = True)

In [11]:
## Check the number of null values missing value in HDB Branch Name feature
df["HDB BRANCH NAME"].isnull().sum()

0

In [12]:
## For all the object datatype other than Cibil Score and Application status fill all the blank values in respective categorical features  with their mode values.
for i in df.columns:
  if df[i].dtype == "object" and i != "Cibil Score" and i != "Application Status":
    df[i].fillna(df[i].mode()[0], inplace = True)

In [13]:
## Check the number of null values/missing values in each feature
df.isnull().sum()

DEALER ID                                 0
HDB BRANCH NAME                           0
AADHAR VERIFIED                           0
Cibil Score                            4297
MOBILE VERIFICATION                       0
TOTAL ASSET COST                       5108
APPLIED AMOUNT                            0
MARITAL STATUS                            0
GENDER                                    0
AGE                                       0
ADDRESS TYPE                              0
EMPLOY CONSTITUTION                       0
vpa                                       0
Phone Social Premium.amazon            1916
Phone Social Premium.byjus             1948
Phone Social Premium.flipkart          1832
Phone Social Premium.housing           1776
Phone Social Premium.indiamart         1775
Phone Social Premium.instagram         6630
Phone Social Premium.jeevansaathi      1829
Phone Social Premium.microsoft         1872
Phone Social Premium.paytm             1757
Phone Social Premium.shaadi            1779
Phone Social Premium.skype             1785
Phone Social Premium.toi               1943
Phone Social Premium.zoho              1782
phone_phoneFootprintStrengthOverall       0
Application Status                        0
dtype: int64

In [14]:
## Converting Cibil score to numeric feature
df['Cibil Score']  = pd.to_numeric(df['Cibil Score'], errors = 'coerce')

In [15]:
## Filling all the blank values with their mean
df['Cibil Score'].fillna(df['Cibil Score'].mean(), inplace = True)

In [16]:
## Check the number of null values in cibil score feature
df['Cibil Score'].isnull().sum()

0

In [17]:
df.dtypes

DEALER ID                                int64
HDB BRANCH NAME                         object
AADHAR VERIFIED                         object
Cibil Score                            float64
MOBILE VERIFICATION                       bool
TOTAL ASSET COST                       float64
APPLIED AMOUNT                           int64
MARITAL STATUS                          object
GENDER                                  object
AGE                                      int64
ADDRESS TYPE                            object
EMPLOY CONSTITUTION                     object
vpa                                     object
Phone Social Premium.amazon            float64
Phone Social Premium.byjus             float64
Phone Social Premium.flipkart          float64
Phone Social Premium.housing           float64
Phone Social Premium.indiamart         float64
Phone Social Premium.instagram         float64
Phone Social Premium.jeevansaathi      float64
Phone Social Premium.microsoft         float64
Phone Social Premium.paytm             float64
Phone Social Premium.shaadi            float64
Phone Social Premium.skype             float64
Phone Social Premium.toi               float64
Phone Social Premium.zoho              float64
phone_phoneFootprintStrengthOverall     object
Application Status                      object
dtype: object

In [18]:
## Converting all the features which start with Phone or phone keyword to object datatype
for i in df.columns:
  if i.startswith("Phone") or i.startswith("phone"):
    df[i] = df[i].astype(object)

In [19]:
df.dtypes

DEALER ID                                int64
HDB BRANCH NAME                         object
AADHAR VERIFIED                         object
Cibil Score                            float64
MOBILE VERIFICATION                       bool
TOTAL ASSET COST                       float64
APPLIED AMOUNT                           int64
MARITAL STATUS                          object
GENDER                                  object
AGE                                      int64
ADDRESS TYPE                            object
EMPLOY CONSTITUTION                     object
vpa                                     object
Phone Social Premium.amazon             object
Phone Social Premium.byjus              object
Phone Social Premium.flipkart           object
Phone Social Premium.housing            object
Phone Social Premium.indiamart          object
Phone Social Premium.instagram          object
Phone Social Premium.jeevansaathi       object
Phone Social Premium.microsoft          object
Phone Social Premium.paytm              object
Phone Social Premium.shaadi             object
Phone Social Premium.skype              object
Phone Social Premium.toi                object
Phone Social Premium.zoho               object
phone_phoneFootprintStrengthOverall     object
Application Status                      object
dtype: object

In [20]:
## Replacing all the blank or null value with the mean of application status
for i in df.columns:
  if df[i].dtype == "object" and i!="Application Status":
    df[i].fillna(df[i].mode()[0], inplace = True)

In [21]:
## Replace all the blank or null values of the feature Total Asset Cost with their mean
df["TOTAL ASSET COST"].fillna(df["TOTAL ASSET COST"].mean(), inplace=True)

In [22]:
df.head()

,DEALER ID,HDB BRANCH NAME,AADHAR VERIFIED,Cibil Score,MOBILE VERIFICATION,TOTAL ASSET COST,APPLIED AMOUNT,MARITAL STATUS,GENDER,AGE,...,Phone Social Premium.instagram,Phone Social Premium.jeevansaathi,Phone Social Premium.microsoft,Phone Social Premium.paytm,Phone Social Premium.shaadi,Phone Social Premium.skype,Phone Social Premium.toi,Phone Social Premium.zoho,phone_phoneFootprintStrengthOverall,Application Status
0,106989,DELHI-SF,NO,726.000000,True,95041.000000,85000,Married,Male,44,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,High,APPROVED
1,108975,PATNA-SF,NO,706.402118,True,97612.518397,90000,Married,Male,25,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,High,APPROVED
2,111004,DARJEELING-SF,NO,737.000000,True,119436.000000,75000,Single,Male,22,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Low,APPROVED
3,192020,SAHARANPUR-SF,NO,713.000000,True,87000.000000,78500,Single,Male,24,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,High,APPROVED
4,55095,MODASA-SF,NO,669.000000,True,97612.518397,70000,Married,Male,33,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,High,DECLINED

In [23]:
df.isnull().sum()

DEALER ID                              0
HDB BRANCH NAME                        0
AADHAR VERIFIED                        0
Cibil Score                            0
MOBILE VERIFICATION                    0
TOTAL ASSET COST                       0
APPLIED AMOUNT                         0
MARITAL STATUS                         0
GENDER                                 0
AGE                                    0
ADDRESS TYPE                           0
EMPLOY CONSTITUTION                    0
vpa                                    0
Phone Social Premium.amazon            0
Phone Social Premium.byjus             0
Phone Social Premium.flipkart          0
Phone Social Premium.housing           0
Phone Social Premium.indiamart         0
Phone Social Premium.instagram         0
Phone Social Premium.jeevansaathi      0
Phone Social Premium.microsoft         0
Phone Social Premium.paytm             0
Phone Social Premium.shaadi            0
Phone Social Premium.skype             0
Phone Social Premium.toi               0
Phone Social Premium.zoho              0
phone_phoneFootprintStrengthOverall    0
Application Status                     0
dtype: int64

### Label encoding

In [24]:
## Finding the number of unique values of categorical columns
cat_columns = [x for x in df.columns if df[x].dtype=='object']
for i in cat_columns:
  print(f"No of unique values in {i} = {df[i].nunique()}")

No of unique values in HDB BRANCH NAME = 542
No of unique values in AADHAR VERIFIED = 1
No of unique values in MARITAL STATUS = 2
No of unique values in GENDER = 2
No of unique values in ADDRESS TYPE = 12
No of unique values in EMPLOY CONSTITUTION = 2
No of unique values in vpa = 40
No of unique values in phone_phoneFootprintStrengthOverall = 5
No of unique values in Application Status = 2

In [25]:
## Doing label encoding to convert all  the categorical feature into numerical feature
from sklearn.preprocessing import LabelEncoder
lc = LabelEncoder()
one_cat_columns = cat_columns[:-1]
print(one_cat_columns)
for i in one_cat_columns:
  df[i] = lc.fit_transform(df[i])

['HDB BRANCH NAME', 'AADHAR VERIFIED', 'MARITAL STATUS', 'GENDER', 'ADDRESS TYPE', 'EMPLOY CONSTITUTION', 'vpa', 'phone_phoneFootprintStrengthOverall']

In [26]:
df.dtypes

DEALER ID                                int64
HDB BRANCH NAME                          int64
AADHAR VERIFIED                          int64
Cibil Score                            float64
MOBILE VERIFICATION                       bool
TOTAL ASSET COST                       float64
APPLIED AMOUNT                           int64
MARITAL STATUS                           int64
GENDER                                   int64
AGE                                      int64
ADDRESS TYPE                             int64
EMPLOY CONSTITUTION                      int64
vpa                                      int64
Phone Social Premium.amazon            float64
Phone Social Premium.byjus             float64
Phone Social Premium.flipkart          float64
Phone Social Premium.housing           float64
Phone Social Premium.indiamart         float64
Phone Social Premium.instagram         float64
Phone Social Premium.jeevansaathi      float64
Phone Social Premium.microsoft         float64
Phone Social Premium.paytm             float64
Phone Social Premium.shaadi            float64
Phone Social Premium.skype             float64
Phone Social Premium.toi               float64
Phone Social Premium.zoho              float64
phone_phoneFootprintStrengthOverall      int64
Application Status                      object
dtype: object

In [27]:
df.dtypes

DEALER ID                                int64
HDB BRANCH NAME                          int64
AADHAR VERIFIED                          int64
Cibil Score                            float64
MOBILE VERIFICATION                       bool
TOTAL ASSET COST                       float64
APPLIED AMOUNT                           int64
MARITAL STATUS                           int64
GENDER                                   int64
AGE                                      int64
ADDRESS TYPE                             int64
EMPLOY CONSTITUTION                      int64
vpa                                      int64
Phone Social Premium.amazon            float64
Phone Social Premium.byjus             float64
Phone Social Premium.flipkart          float64
Phone Social Premium.housing           float64
Phone Social Premium.indiamart         float64
Phone Social Premium.instagram         float64
Phone Social Premium.jeevansaathi      float64
Phone Social Premium.microsoft         float64
Phone Social Premium.paytm             float64
Phone Social Premium.shaadi            float64
Phone Social Premium.skype             float64
Phone Social Premium.toi               float64
Phone Social Premium.zoho              float64
phone_phoneFootprintStrengthOverall      int64
Application Status                      object
dtype: object

In [28]:
## Converting Mobile Verification feature to integer datatype from object datatype
df['MOBILE VERIFICATION'] = df['MOBILE VERIFICATION'].astype(int)
df.dtypes

DEALER ID                                int64
HDB BRANCH NAME                          int64
AADHAR VERIFIED                          int64
Cibil Score                            float64
MOBILE VERIFICATION                      int64
TOTAL ASSET COST                       float64
APPLIED AMOUNT                           int64
MARITAL STATUS                           int64
GENDER                                   int64
AGE                                      int64
ADDRESS TYPE                             int64
EMPLOY CONSTITUTION                      int64
vpa                                      int64
Phone Social Premium.amazon            float64
Phone Social Premium.byjus             float64
Phone Social Premium.flipkart          float64
Phone Social Premium.housing           float64
Phone Social Premium.indiamart         float64
Phone Social Premium.instagram         float64
Phone Social Premium.jeevansaathi      float64
Phone Social Premium.microsoft         float64
Phone Social Premium.paytm             float64
Phone Social Premium.shaadi            float64
Phone Social Premium.skype             float64
Phone Social Premium.toi               float64
Phone Social Premium.zoho              float64
phone_phoneFootprintStrengthOverall      int64
Application Status                      object
dtype: object

In [29]:
## Reading all the columns
df.columns

Index(['DEALER ID', 'HDB BRANCH NAME', 'AADHAR VERIFIED', 'Cibil Score',
       'MOBILE VERIFICATION', 'TOTAL ASSET COST', 'APPLIED AMOUNT',
       'MARITAL STATUS', 'GENDER', 'AGE', 'ADDRESS TYPE',
       'EMPLOY CONSTITUTION', 'vpa', 'Phone Social Premium.amazon',
       'Phone Social Premium.byjus', 'Phone Social Premium.flipkart',
       'Phone Social Premium.housing', 'Phone Social Premium.indiamart',
       'Phone Social Premium.instagram', 'Phone Social Premium.jeevansaathi',
       'Phone Social Premium.microsoft', 'Phone Social Premium.paytm',
       'Phone Social Premium.shaadi', 'Phone Social Premium.skype',
       'Phone Social Premium.toi', 'Phone Social Premium.zoho',
       'phone_phoneFootprintStrengthOverall', 'Application Status'],
      dtype='object')

In [30]:
## Doing one hot encoding for target feature
df['Application Status'] = pd.get_dummies(df['Application Status'], drop_first=True, dtype=int)

In [31]:
df.head()

,DEALER ID,HDB BRANCH NAME,AADHAR VERIFIED,Cibil Score,MOBILE VERIFICATION,TOTAL ASSET COST,APPLIED AMOUNT,MARITAL STATUS,GENDER,AGE,...,Phone Social Premium.instagram,Phone Social Premium.jeevansaathi,Phone Social Premium.microsoft,Phone Social Premium.paytm,Phone Social Premium.shaadi,Phone Social Premium.skype,Phone Social Premium.toi,Phone Social Premium.zoho,phone_phoneFootprintStrengthOverall,Application Status
0,106989,140,0,726.000000,1,95041.000000,85000,0,1,44,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,0
1,108975,397,0,706.402118,1,97612.518397,90000,0,1,25,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0
2,111004,130,0,737.000000,1,119436.000000,75000,1,1,22,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
3,192020,446,0,713.000000,1,87000.000000,78500,1,1,24,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,0
4,55095,340,0,669.000000,1,97612.518397,70000,0,1,33,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,1

In [32]:
## Spiliting the data into target and non target columns
X = df.drop('Application Status', axis=1).values
y = df['Application Status'].values

In [33]:
df.head()

,DEALER ID,HDB BRANCH NAME,AADHAR VERIFIED,Cibil Score,MOBILE VERIFICATION,TOTAL ASSET COST,APPLIED AMOUNT,MARITAL STATUS,GENDER,AGE,...,Phone Social Premium.instagram,Phone Social Premium.jeevansaathi,Phone Social Premium.microsoft,Phone Social Premium.paytm,Phone Social Premium.shaadi,Phone Social Premium.skype,Phone Social Premium.toi,Phone Social Premium.zoho,phone_phoneFootprintStrengthOverall,Application Status
0,106989,140,0,726.000000,1,95041.000000,85000,0,1,44,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,0
1,108975,397,0,706.402118,1,97612.518397,90000,0,1,25,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0
2,111004,130,0,737.000000,1,119436.000000,75000,1,1,22,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0
3,192020,446,0,713.000000,1,87000.000000,78500,1,1,24,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,0
4,55095,340,0,669.000000,1,97612.518397,70000,0,1,33,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0,1

In [34]:
## Doing train test split for training data so as to get validation accuracy
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=1)

In [35]:
## Appying standard scaling - This is particularly important when using algorithms that are sensitive to the scale of the data, like SVM, Random Forest
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_valid = sc.transform(X_valid)

In [36]:
## Training the data using different models (Logistic Resgression, Random Forest Classifier, Support Vector Machine)
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

rf = RandomForestClassifier(n_estimators=1000)
lr = LogisticRegression(penalty='l2')
svc = SVC(kernel='rbf', degree=7)
lr.fit(X_train, y_train)
rf.fit(X_train, y_train)
svc.fit(X_train, y_train)

SVC(degree=7)

In [37]:
## Doing evaluation using evaluation metrices
from sklearn.metrics import accuracy_score, precision_score, recall_score

pred = lr.predict(X_train)
pred_lr = rf.predict(X_train)
pred_svc= svc.predict(X_train)
print("Accuracy using logistic regression", accuracy_score(pred, y_train))
print("Precision using logistic regression", precision_score(pred, y_train))
print("Recall using logistic regression",recall_score(pred, y_train))
print("Accuracy using Random Forest", accuracy_score(pred_lr, y_train))
print("Precision using Random Forest",precision_score(pred_svc, y_train))
print("Recall using Random Forest",recall_score(pred_svc, y_train))
print("Accuracy using Support Vector Machine", accuracy_score(pred_svc, y_train))
print("Precision using Support Vector Machine",precision_score(pred_svc, y_train))
print("Recall using Support Vector Machine",recall_score(pred_svc, y_train))


pred = lr.predict(X_valid)
pred_lr = rf.predict(X_valid)
pred_svc= svc.predict(X_valid)
print("Accuracy score using logistic regression", accuracy_score(pred, y_valid))
print("Precision using logistic regression", precision_score(pred, y_valid))
print("Recall using logistic regression",recall_score(pred, y_valid))
print("Accuracy score using Random Forest", accuracy_score(pred_lr, y_valid))
print("Precision using Random Forest", precision_score(pred_lr, y_valid))
print("Recall using Random Forest",recall_score(pred_lr, y_valid))
print("Accuracy score using Support Vector Classifier", accuracy_score(pred_svc, y_valid))
print("Precision using Support Vector Classifier", precision_score(pred_svc, y_valid))
print("Recall using Support Vector Classifier", recall_score(pred_svc, y_valid))

Accuracy using logistic regression 0.81125
Precision using logistic regression 0.5728813559322034
Recall using logistic regression 0.8017923036373221
Accuracy using Random Forest 0.99975
Precision using Random Forest 0.6105461393596987
Recall using Random Forest 0.8872468527640941
Accuracy using Support Vector Machine 0.845
Precision using Support Vector Machine 0.6105461393596987
Recall using Support Vector Machine 0.8872468527640941
Accuracy score using logistic regression 0.8125
Precision using logistic regression 0.5868263473053892
Recall using logistic regression 0.7983706720977597
Accuracy score using Random Forest 0.893
Precision using Random Forest 0.8083832335329342
Recall using Random Forest 0.8626198083067093
Accuracy score using Support Vector Classifier 0.8185
Precision using Support Vector Classifier 0.5733532934131736
Recall using Support Vector Classifier 0.8308026030368764

In [38]:
## Performing hypperparameter tuning in order to reduce overfitting in case of random forest
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

grid_search = GridSearchCV(RandomForestClassifier(), param_grid, cv=2)
grid_search.fit(X_train, y_train)
print(f"Best parameters: {grid_search.best_params_}")

Best parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 200}

In [39]:
## Doing evaluation using evaluation metrices
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred = rf.predict(X_train)
y_pred_test = rf.predict(X_valid)
print("Accuracy using Random Forest", accuracy_score(y_pred, y_train))
print("Precision using Random Forest",precision_score(y_pred, y_train))
print("Recall using Random Forest",recall_score(y_pred, y_train))
print("Accuracy score using Random Forest", accuracy_score(y_pred_test, y_valid))
print("Precision using Random Forest", precision_score(y_pred_test, y_valid))
print("Recall using Random Forest",recall_score(y_pred_test, y_valid))

Accuracy using Random Forest 0.999625
Precision using Random Forest 0.9992467043314501
Recall using Random Forest 0.9996232102486813
Accuracy score using Random Forest 0.8875
Precision using Random Forest 0.8023952095808383
Recall using Random Forest 0.8521462639109698

### For testing

In [40]:
# # Read the Dataset
df_pre = pd.read_csv("/content/drive/MyDrive/Assignment_Test.csv")
df_pre.head()

,UID,DEALER ID,APPLICATION LOGIN DATE,HDB BRANCH NAME,HDB BRANCH STATE,FIRST NAME,MIDDLE NAME,LAST NAME,mobile,AADHAR VERIFIED,...,Phone Social Premium.rummycircle,Phone Social Premium.shaadi,Phone Social Premium.skype,Phone Social Premium.toi,Phone Social Premium.whatsapp,Phone Social Premium.yatra,Phone Social Premium.zoho,phone_digitalage,phone_nameMatchScore,phone_phoneFootprintStrengthOverall
0,1844045271814558464,105615,07/12/22,HUBLI-SF,NaN,VENUGOPAL,H,BHARADHVAJ,7019759674,NO,...,NaN,0.0,0.0,0.0,0.0,NaN,0.0,676,100.0,Medium
1,1840349097823778816,91593,07/14/2022,SATNA-SF,MADHYA PRADESH,SHIVDHAR,NaN,CHAUDHARY,7697884828,NO,...,NaN,0.0,0.0,NaN,0.0,NaN,0.0,897,-1.0,Low
2,1488102613362294272,74152,07/07/22,LUCKNOW-SF,UTTAR PRADESH,MANISH,NaN,VERMA,8840079825,NO,...,NaN,0.0,1.0,0.0,1.0,NaN,0.0,839,100.0,Medium
3,555529923942874624,110164,07/13/2022,KOLLAM-SF,KERALA,DEEPU,RAVEENDRAN,RAVEENDRAN,8089276854,NO,...,NaN,0.0,0.0,0.0,NaN,NaN,0.0,2050,-1.0,Low
4,1010213070486150912,113037,07/08/22,PURI-SF,ORISSA,AKASHA,NaN,PRADHAN,9337511958,NO,...,NaN,0.0,0.0,0.0,NaN,NaN,0.0,-1,-1.0,Very Low

In [41]:
# ## Make a list of redundant columns and drop redundant columns
df = df_pre
df_list = ["UID","APPLICATION LOGIN DATE", "HDB BRANCH STATE", "FIRST NAME", "MIDDLE NAME", "LAST NAME", "mobile" , "DEALER NAME", "ASSET CTG", "ASSET MODEL NO", "PRIMARY ASSET MAKE", "Primary Asset Model No", "Personal Email Address", "DOB", "EMPLOYER NAME", "EMPLOYER TYPE", "Pan Name", "name", "upi_name", "Phone Social Premium.a23games", "Phone Social Premium.isWABusiness", "Phone Social Premium.jiomart", "Phone Social Premium.my11", "Phone Social Premium.rummycircle", "Phone Social Premium.whatsapp", "Phone Social Premium.yatra", "phone_digitalage", "phone_nameMatchScore"]
df.drop(labels = df_list, axis=1, inplace = True)

In [42]:
df.head()

,DEALER ID,HDB BRANCH NAME,AADHAR VERIFIED,Cibil Score,MOBILE VERIFICATION,TOTAL ASSET COST,APPLIED AMOUNT,MARITAL STATUS,GENDER,AGE,...,Phone Social Premium.indiamart,Phone Social Premium.instagram,Phone Social Premium.jeevansaathi,Phone Social Premium.microsoft,Phone Social Premium.paytm,Phone Social Premium.shaadi,Phone Social Premium.skype,Phone Social Premium.toi,Phone Social Premium.zoho,phone_phoneFootprintStrengthOverall
0,105615,HUBLI-SF,NO,757,True,95352.0,88000,Married,Male,56,...,1.0,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Medium
1,91593,SATNA-SF,NO,750,True,75371.0,75000,Married,Male,42,...,1.0,NaN,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Low
2,74152,LUCKNOW-SF,NO,710,True,94983.0,93000,Single,Male,25,...,1.0,NaN,0.0,1.0,1.0,0.0,1.0,0.0,0.0,Medium
3,110164,KOLLAM-SF,NO,695,True,NaN,95000,NaN,Male,34,...,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Low
4,113037,PURI-SF,NO,NaN,True,90277.0,83000,Single,Male,24,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Very Low

In [43]:
df.isnull().sum()

DEALER ID                                 0
HDB BRANCH NAME                           0
AADHAR VERIFIED                           0
Cibil Score                             842
MOBILE VERIFICATION                       0
TOTAL ASSET COST                       1022
APPLIED AMOUNT                            0
MARITAL STATUS                          981
GENDER                                    0
AGE                                       0
ADDRESS TYPE                            635
EMPLOY CONSTITUTION                     994
vpa                                     554
Phone Social Premium.amazon             117
Phone Social Premium.byjus               23
Phone Social Premium.flipkart            45
Phone Social Premium.housing             23
Phone Social Premium.indiamart           23
Phone Social Premium.instagram         1388
Phone Social Premium.jeevansaathi        38
Phone Social Premium.microsoft           29
Phone Social Premium.paytm               25
Phone Social Premium.shaadi              26
Phone Social Premium.skype               26
Phone Social Premium.toi                 64
Phone Social Premium.zoho                23
phone_phoneFootprintStrengthOverall       1
dtype: int64

In [44]:
df.isnull().sum()

DEALER ID                                 0
HDB BRANCH NAME                           0
AADHAR VERIFIED                           0
Cibil Score                             842
MOBILE VERIFICATION                       0
TOTAL ASSET COST                       1022
APPLIED AMOUNT                            0
MARITAL STATUS                          981
GENDER                                    0
AGE                                       0
ADDRESS TYPE                            635
EMPLOY CONSTITUTION                     994
vpa                                     554
Phone Social Premium.amazon             117
Phone Social Premium.byjus               23
Phone Social Premium.flipkart            45
Phone Social Premium.housing             23
Phone Social Premium.indiamart           23
Phone Social Premium.instagram         1388
Phone Social Premium.jeevansaathi        38
Phone Social Premium.microsoft           29
Phone Social Premium.paytm               25
Phone Social Premium.shaadi              26
Phone Social Premium.skype               26
Phone Social Premium.toi                 64
Phone Social Premium.zoho                23
phone_phoneFootprintStrengthOverall       1
dtype: int64

In [45]:
## Converting Cibil Score into numerical feature
df['Cibil Score']  = pd.to_numeric(df['Cibil Score'], errors = 'coerce')

In [46]:
## Fill all the blank values in Cibil score with its mean
df['Cibil Score'].fillna(df['Cibil Score'].mean(), inplace = True)

In [47]:
df['Cibil Score'].isnull().sum()

0

In [48]:
df.dtypes

DEALER ID                                int64
HDB BRANCH NAME                         object
AADHAR VERIFIED                         object
Cibil Score                            float64
MOBILE VERIFICATION                       bool
TOTAL ASSET COST                       float64
APPLIED AMOUNT                           int64
MARITAL STATUS                          object
GENDER                                  object
AGE                                      int64
ADDRESS TYPE                            object
EMPLOY CONSTITUTION                     object
vpa                                     object
Phone Social Premium.amazon            float64
Phone Social Premium.byjus             float64
Phone Social Premium.flipkart          float64
Phone Social Premium.housing           float64
Phone Social Premium.indiamart         float64
Phone Social Premium.instagram         float64
Phone Social Premium.jeevansaathi      float64
Phone Social Premium.microsoft         float64
Phone Social Premium.paytm             float64
Phone Social Premium.shaadi            float64
Phone Social Premium.skype             float64
Phone Social Premium.toi               float64
Phone Social Premium.zoho              float64
phone_phoneFootprintStrengthOverall     object
dtype: object

In [49]:
## Converting all the features which start with Phone or phone keyword to object datatype
for i in df.columns:
  if i.startswith("Phone") or i.startswith("phone"):
    df[i] = df[i].astype(object)

In [50]:
## For all the object datatype fill all the blank values in respective categorical features with their mode values.
for i in df.columns:
  if df[i].dtype == "object":
    df[i].fillna(df[i].mode()[0], inplace = True)

In [51]:
df["TOTAL ASSET COST"].fillna(df["TOTAL ASSET COST"].mean(), inplace=True)

In [52]:
df.isnull().sum()

DEALER ID                              0
HDB BRANCH NAME                        0
AADHAR VERIFIED                        0
Cibil Score                            0
MOBILE VERIFICATION                    0
TOTAL ASSET COST                       0
APPLIED AMOUNT                         0
MARITAL STATUS                         0
GENDER                                 0
AGE                                    0
ADDRESS TYPE                           0
EMPLOY CONSTITUTION                    0
vpa                                    0
Phone Social Premium.amazon            0
Phone Social Premium.byjus             0
Phone Social Premium.flipkart          0
Phone Social Premium.housing           0
Phone Social Premium.indiamart         0
Phone Social Premium.instagram         0
Phone Social Premium.jeevansaathi      0
Phone Social Premium.microsoft         0
Phone Social Premium.paytm             0
Phone Social Premium.shaadi            0
Phone Social Premium.skype             0
Phone Social Premium.toi               0
Phone Social Premium.zoho              0
phone_phoneFootprintStrengthOverall    0
dtype: int64

In [53]:
df.head()

,DEALER ID,HDB BRANCH NAME,AADHAR VERIFIED,Cibil Score,MOBILE VERIFICATION,TOTAL ASSET COST,APPLIED AMOUNT,MARITAL STATUS,GENDER,AGE,...,Phone Social Premium.indiamart,Phone Social Premium.instagram,Phone Social Premium.jeevansaathi,Phone Social Premium.microsoft,Phone Social Premium.paytm,Phone Social Premium.shaadi,Phone Social Premium.skype,Phone Social Premium.toi,Phone Social Premium.zoho,phone_phoneFootprintStrengthOverall
0,105615,HUBLI-SF,NO,757.000000,True,95352.000000,88000,Married,Male,56,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Medium
1,91593,SATNA-SF,NO,750.000000,True,75371.000000,75000,Married,Male,42,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Low
2,74152,LUCKNOW-SF,NO,710.000000,True,94983.000000,93000,Single,Male,25,...,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,Medium
3,110164,KOLLAM-SF,NO,695.000000,True,97679.605317,95000,Married,Male,34,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Low
4,113037,PURI-SF,NO,706.444541,True,90277.000000,83000,Single,Male,24,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,Very Low

In [54]:
## Check the number of unique values in object datatype features
cat_columns = [x for x in df.columns if df[x].dtype=='object']
for i in cat_columns:
  print(f"No of unique values in {i} = {df[i].nunique()}")

No of unique values in HDB BRANCH NAME = 406
No of unique values in AADHAR VERIFIED = 1
No of unique values in MARITAL STATUS = 2
No of unique values in GENDER = 2
No of unique values in ADDRESS TYPE = 7
No of unique values in EMPLOY CONSTITUTION = 2
No of unique values in vpa = 28
No of unique values in phone_phoneFootprintStrengthOverall = 5

In [55]:
## Perform label encoding
from sklearn.preprocessing import LabelEncoder
lc = LabelEncoder()
one_cat_columns = cat_columns[:]
print(one_cat_columns)
for i in one_cat_columns:
  df[i] = lc.fit_transform(df[i])

['HDB BRANCH NAME', 'AADHAR VERIFIED', 'MARITAL STATUS', 'GENDER', 'ADDRESS TYPE', 'EMPLOY CONSTITUTION', 'vpa', 'phone_phoneFootprintStrengthOverall']

In [56]:
## Convert datatype of MOBILE VERIFICATION Feature from objct to integer
df['MOBILE VERIFICATION'] = df['MOBILE VERIFICATION'].astype(int)

In [57]:
df.dtypes

DEALER ID                                int64
HDB BRANCH NAME                          int64
AADHAR VERIFIED                          int64
Cibil Score                            float64
MOBILE VERIFICATION                      int64
TOTAL ASSET COST                       float64
APPLIED AMOUNT                           int64
MARITAL STATUS                           int64
GENDER                                   int64
AGE                                      int64
ADDRESS TYPE                             int64
EMPLOY CONSTITUTION                      int64
vpa                                      int64
Phone Social Premium.amazon            float64
Phone Social Premium.byjus             float64
Phone Social Premium.flipkart          float64
Phone Social Premium.housing           float64
Phone Social Premium.indiamart         float64
Phone Social Premium.instagram         float64
Phone Social Premium.jeevansaathi      float64
Phone Social Premium.microsoft         float64
Phone Social Premium.paytm             float64
Phone Social Premium.shaadi            float64
Phone Social Premium.skype             float64
Phone Social Premium.toi               float64
Phone Social Premium.zoho              float64
phone_phoneFootprintStrengthOverall      int64
dtype: object

In [58]:
df.columns

Index(['DEALER ID', 'HDB BRANCH NAME', 'AADHAR VERIFIED', 'Cibil Score',
       'MOBILE VERIFICATION', 'TOTAL ASSET COST', 'APPLIED AMOUNT',
       'MARITAL STATUS', 'GENDER', 'AGE', 'ADDRESS TYPE',
       'EMPLOY CONSTITUTION', 'vpa', 'Phone Social Premium.amazon',
       'Phone Social Premium.byjus', 'Phone Social Premium.flipkart',
       'Phone Social Premium.housing', 'Phone Social Premium.indiamart',
       'Phone Social Premium.instagram', 'Phone Social Premium.jeevansaathi',
       'Phone Social Premium.microsoft', 'Phone Social Premium.paytm',
       'Phone Social Premium.shaadi', 'Phone Social Premium.skype',
       'Phone Social Premium.toi', 'Phone Social Premium.zoho',
       'phone_phoneFootprintStrengthOverall'],
      dtype='object')

In [59]:
df.head()

,DEALER ID,HDB BRANCH NAME,AADHAR VERIFIED,Cibil Score,MOBILE VERIFICATION,TOTAL ASSET COST,APPLIED AMOUNT,MARITAL STATUS,GENDER,AGE,...,Phone Social Premium.indiamart,Phone Social Premium.instagram,Phone Social Premium.jeevansaathi,Phone Social Premium.microsoft,Phone Social Premium.paytm,Phone Social Premium.shaadi,Phone Social Premium.skype,Phone Social Premium.toi,Phone Social Premium.zoho,phone_phoneFootprintStrengthOverall
0,105615,166,0,757.000000,1,95352.000000,88000,0,1,56,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2
1,91593,344,0,750.000000,1,75371.000000,75000,0,1,42,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,74152,237,0,710.000000,1,94983.000000,93000,1,1,25,...,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,2
3,110164,216,0,695.000000,1,97679.605317,95000,0,1,34,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,113037,305,0,706.444541,1,90277.000000,83000,1,1,24,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4

In [60]:
df.dtypes

DEALER ID                                int64
HDB BRANCH NAME                          int64
AADHAR VERIFIED                          int64
Cibil Score                            float64
MOBILE VERIFICATION                      int64
TOTAL ASSET COST                       float64
APPLIED AMOUNT                           int64
MARITAL STATUS                           int64
GENDER                                   int64
AGE                                      int64
ADDRESS TYPE                             int64
EMPLOY CONSTITUTION                      int64
vpa                                      int64
Phone Social Premium.amazon            float64
Phone Social Premium.byjus             float64
Phone Social Premium.flipkart          float64
Phone Social Premium.housing           float64
Phone Social Premium.indiamart         float64
Phone Social Premium.instagram         float64
Phone Social Premium.jeevansaathi      float64
Phone Social Premium.microsoft         float64
Phone Social Premium.paytm             float64
Phone Social Premium.shaadi            float64
Phone Social Premium.skype             float64
Phone Social Premium.toi               float64
Phone Social Premium.zoho              float64
phone_phoneFootprintStrengthOverall      int64
dtype: object

In [61]:
df.head()

,DEALER ID,HDB BRANCH NAME,AADHAR VERIFIED,Cibil Score,MOBILE VERIFICATION,TOTAL ASSET COST,APPLIED AMOUNT,MARITAL STATUS,GENDER,AGE,...,Phone Social Premium.indiamart,Phone Social Premium.instagram,Phone Social Premium.jeevansaathi,Phone Social Premium.microsoft,Phone Social Premium.paytm,Phone Social Premium.shaadi,Phone Social Premium.skype,Phone Social Premium.toi,Phone Social Premium.zoho,phone_phoneFootprintStrengthOverall
0,105615,166,0,757.000000,1,95352.000000,88000,0,1,56,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2
1,91593,344,0,750.000000,1,75371.000000,75000,0,1,42,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
2,74152,237,0,710.000000,1,94983.000000,93000,1,1,25,...,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,2
3,110164,216,0,695.000000,1,97679.605317,95000,0,1,34,...,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1
4,113037,305,0,706.444541,1,90277.000000,83000,1,1,24,...,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4

In [62]:
## Defining the test data on test data
X_test = df

In [63]:
## Performing standard scaling
X_test = sc.transform(X_test)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:458: UserWarning: X has feature names, but StandardScaler was fitted without feature names
  warnings.warn(

In [64]:
## Performing predictons
pred_lr = rf.predict(X_test)

In [65]:
(pred_lr == False).sum()

1956

In [66]:
pred_lr = pred_lr > 0
print(pred_lr)

[False False False ... False False False]

In [67]:
# Create a DataFrame for predictions
results = pd.DataFrame({"UID" : pd.read_csv("/content/drive/MyDrive/Assignment_Test.csv")["UID"],
                        "Prediction": pred_lr
})

In [68]:
results

                      UID  Prediction
0     1844045271814558464       False
1     1840349097823778816       False
2     1488102613362294272       False
3      555529923942874624       False
4     1010213070486150912       False
...                   ...         ...
1995  1595862360559879424       False
1996   879889749720017664       False
1997   242909456443720192       False
1998   138725642700761856       False
1999  1680321200653072640       False

[2000 rows x 2 columns]

In [69]:
# Save the predictions to a CSV file
results.to_csv('predictions.csv', index=False)